# SPDX-License-Identifier: GPL-2.0
DTC_FLAGS += -p 4096
dtb-$(CONFIG_ARCH_MA35D1)    += som35d1f-255.dtb

dtb-$(CONFIG_ARCH_MA35D0)    += ma35d0-iot-256m.dtb

dtb-$(CONFIG_ARCH_MA35H0)    += ma35h0-hmi-128m.dtb

always          := $(dtb-y)
clean-files     := *.dtb

